// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetTrafficStats(arg1) {
  return window['go']['main']['App']['GetTrafficStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetTrafficStats(arg1) {
  return window['go']['main']['App']['ResetTrafficStats'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function TestUDP(arg1) {
  return window['go']['main']['App']['TestUDP'](arg1);
}

export function UpdateRule(arg1) {
  return window['go']['main']['App']['UpdateRule'](arg1);
}
