// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRule(arg1:main.SocksRule):Promise<string>;

export function DeleteRule(arg1:string):Promise<boolean>;

export function GetRules():Promise<Array<main.SocksRule>>;

export function GetTrafficStats(arg1:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function ResetTrafficStats(arg1:string):Promise<void>;

export function StartServer(arg1:string):Promise<boolean>;

export function StopServer(arg1:string):Promise<boolean>;

export function TestUDP(arg1:string):Promise<string>;

export function UpdateRule(arg1:main.SocksRule):Promise<boolean>;
